### ISSUE TITLE
教室情况停在了9.13~9.19这一周

### ISSUE THREAD

**Issue by 805758907** [Starrah/THUCourseHelper#33]
在4G网和校园网下，访问“信息”->“查看教室情况”，所有教室的情况都显示的是9.13-9.19这一周的情况，没有同步到当前周（10.25-10.31）。
截图：
![bug](https://user-images.githubusercontent.com/50165766/138875924-e8d5aa6c-b37b-4a3c-94f9-ed8108ffb22d.jpg)

**Comment by Starrah** [comment]
后端Java依赖版本问题。已在后端修复，前端无需更新。
