### ISSUE TITLE
无法使用：「获取学期数据失败，请检查网络连接」

### ISSUE THREAD

**Issue by Ethkuil** [Starrah/THUCourseHelper#34]
apk文件来源：
>国内CDN高速下载链接
>https://cos.starrah.cn/THUCourseHelper.apk

网络环境：Tsinghua Secure

请问是本软件现在无法使用了吗？

**Comment by Starrah** [comment]
抱歉我之前忘记添加秋季学期数据了。现已添加，您再试试。
还是不行的话可以再reopen。
